
/* MAIN */

const FLAG_OWNER_TYPE_SUPER_ROOT = 0b000;
const FLAG_OWNER_TYPE_ROOT = 0b001;
const FLAG_OWNER_TYPE_CONTEXT = 0b010;
const FLAG_OWNER_TYPE_ERROR = 0b011;
const FLAG_OWNER_TYPE_EFFECT = 0b100;
const FLAG_OWNER_TYPE_MEMO = 0b101;
const FLAG_OWNER_TYPE_SUSPENSE = 0b110;
const MASK_OWNER_TYPE = 0b111;

const FLAG_OWNER_DIRTY_NO: number = 0b00000; // The observer is not dirty, for sure
const FLAG_OWNER_DIRTY_MAYBE_NO: number = 0b01000; // The observer is not dirty, possibly
const FLAG_OWNER_DIRTY_MAYBE_YES: number = 0b10000; // The observer is dirty, possibly
const FLAG_OWNER_DIRTY_YES: number = 0b11000; // The observer is dirty, for sure
const MASK_OWNER_DIRTY: number = 0b11000;

const FLAG_OWNER_DISPOSED = 0b100000;

const FLAG_OBSERVABLE_TYPE_WRITABLE = 0b01;
const FLAG_OBSERVABLE_TYPE_READABLE = 0b10;
const FLAG_OBSERVABLE_TYPE_FROZEN = 0b11;
const MASK_OBSERVABLE_TYPE = 0b11;

const FLAG_OBSERVABLE_BOOLEAN = 0b100;

const EMPTY_ARRAY = [];
const EMPTY_OBJECT = {};

const UNAVAILABLE: any = new Proxy ( {}, new Proxy ( {}, { get () { throw new Error ( 'Unavailable value' ) } } ) ); //TSC
const UNINITIALIZED: any = function () {}; //TSC

/* EXPORT */

export {FLAG_OWNER_TYPE_SUPER_ROOT, FLAG_OWNER_TYPE_ROOT, FLAG_OWNER_TYPE_CONTEXT, FLAG_OWNER_TYPE_ERROR, FLAG_OWNER_TYPE_EFFECT, FLAG_OWNER_TYPE_MEMO, FLAG_OWNER_TYPE_SUSPENSE, MASK_OWNER_TYPE};
export {FLAG_OWNER_DIRTY_NO, FLAG_OWNER_DIRTY_MAYBE_NO, FLAG_OWNER_DIRTY_MAYBE_YES, FLAG_OWNER_DIRTY_YES, MASK_OWNER_DIRTY};
export {FLAG_OWNER_DISPOSED};
export {FLAG_OBSERVABLE_TYPE_WRITABLE, FLAG_OBSERVABLE_TYPE_READABLE, FLAG_OBSERVABLE_TYPE_FROZEN, MASK_OBSERVABLE_TYPE};
export {FLAG_OBSERVABLE_BOOLEAN};
export {EMPTY_ARRAY, EMPTY_OBJECT};
export {UNAVAILABLE, UNINITIALIZED};
